-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 15:40:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OpenFoodFacts
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `OpenFoodFacts` ;

-- -----------------------------------------------------
-- Schema OpenFoodFacts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OpenFoodFacts` DEFAULT CHARACTER SET utf8 ;
USE `OpenFoodFacts` ;

-- -----------------------------------------------------
-- Table `OpenFoodFacts`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodFacts`.`product` ;

CREATE TABLE IF NOT EXISTS `OpenFoodFacts`.`product` (
  `id` BIGINT NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NULL,
  `nutriscore_grade` VARCHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenFoodFacts`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodFacts`.`category` ;

CREATE TABLE IF NOT EXISTS `OpenFoodFacts`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(400) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenFoodFacts`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodFacts`.`store` ;

CREATE TABLE IF NOT EXISTS `OpenFoodFacts`.`store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `store_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenFoodFacts`.`substituted_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodFacts`.`substituted_product` ;

CREATE TABLE IF NOT EXISTS `OpenFoodFacts`.`substituted_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `substitution_product_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_substituted_product_product_idx` (`product_id` ASC),
  INDEX `fk_substituted_product_product1_idx` (`substitution_product_id` ASC),
  CONSTRAINT `fk_substituted_product_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `OpenFoodFacts`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_substituted_product_product1`
    FOREIGN KEY (`substitution_product_id`)
    REFERENCES `OpenFoodFacts`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenFoodFacts`.`category_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodFacts`.`category_has_product` ;

CREATE TABLE IF NOT EXISTS `OpenFoodFacts`.`category_has_product` (
  `category_id` INT NOT NULL,
  `product_id` BIGINT NOT NULL,
  PRIMARY KEY (`category_id`, `product_id`),
  INDEX `fk_category_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_category_has_product_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_category_has_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `OpenFoodFacts`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `OpenFoodFacts`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpenFoodFacts`.`store_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpenFoodFacts`.`store_has_product` ;

CREATE TABLE IF NOT EXISTS `OpenFoodFacts`.`store_has_product` (
  `store_id` INT NOT NULL,
  `product_id` BIGINT NOT NULL,
  PRIMARY KEY (`store_id`, `product_id`),
  INDEX `fk_store_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_store_has_product_store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_store_has_product_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `OpenFoodFacts`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_store_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `OpenFoodFacts`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
